;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	kill-rectangle
	string-rectangle
	view-emacs-news
	))

(setq mc/cmds-to-run-once
      '(
	electric-newline-and-maybe-indent
	multiple-cursors-mode
	))
