;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	eval-buffer
	insert-register
	string-rectangle
	))

(setq mc/cmds-to-run-once
      '(
	find-file-read-only
	org-self-insert-command
	))
